---
- name: install jenkins
  hosts: jenkinserver
  tasks:
    - name: jenkins
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-8-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name: downloading jenkins.war file
      get_url:
          url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
          dest: /home/ubuntu
- name: configuring tomcat9 on servers
  hosts: servers
  tasks:
    - name: tomcat9
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat9,b: present,c: yes}
        - {a: tomcat9-admin,b: present,c: no}
    - name:
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9      
      notify: restart tomcat9
  handlers:
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted      
