---
- name: check file f1 and if it doesnot have execute permissions give it
  hosts: all
  tasks:
    - name: check for file f1
      stat:
        path: /tmp/f1
      register: a
    - name: display the output 
      debug:
        var: a
    - name: create file f1
      file:
        name: /tmp/f1
        state: touch
      when: a.stat.exists == false    
    - name: give permission to execute
      file:
        name: /tmp/f1
        mode: 700
      when: a.stat.executable == false    
