---
- name: installing softwares
  hosts: all
  become: yes
  tasks:
    - name: installing apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: check response on url    
    - name: editing html file
      copy:
         content: "there is a one crazy soul out there"
         dest: /var/www/html/index.html
      notify: restart apache
  handlers:
    - name: restart apache
      service:
         name: apache2
         state: restarted    
    - name: check response on url
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.29.249
        - http://172.31.31.248
        - http://172.31.12.236
        - http://172.31.10.17

      
