---
- name: error handling
  hosts: all
  become: yes
  tasks:
    - block:
         - name: install tree using apt
           apt:
             name: tree
             state: present
             update_cache: no
      rescue:
         - name: install tree using yum
           yum:
             name: tree
             state: present
             update_cache: yes
      always:
         - name: printing msg
           debug:
             msg: " there is a life in everysoul"        
