---
- name: installing packages
  hosts: all
  tasks:
    - name:
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree, b: present, c: yes}
        - {a: git, b: present, c: yes}
        - {a: maven, b: latest, c: yes}      
