---
- name: install tree package
  hosts: all
  tasks:
    - name: tree installation on redhat
      yum:
        name: tree
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: tree installation on ubuntu
      apt:
        name: tree
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"    

